#pragma once
//------------------------------------------------------------------------------
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//------------------------------------------------------------------------------


namespace Windows {
    namespace UI {
        namespace Xaml {
            namespace Controls {
                ref class Slider;
                ref class Button;
                ref class AppBar;
                ref class StackPanel;
                ref class TextBox;
                ref class Grid;
                ref class WebView;
                ref class PasswordBox;
                ref class ProgressBar;
                ref class Canvas;
                ref class ListView;
                ref class FlipView;
            }
        }
    }
}

namespace mupdf_cpp
{
    [::Windows::Foundation::Metadata::WebHostHidden]
    partial ref class MainPage : public ::Windows::UI::Xaml::Controls::Page, 
        public ::Windows::UI::Xaml::Markup::IComponentConnector,
        public ::Windows::UI::Xaml::Markup::IComponentConnector2
    {
    public:
        void InitializeComponent();
        virtual void Connect(int connectionId, ::Platform::Object^ target);
        virtual ::Windows::UI::Xaml::Markup::IComponentConnector^ GetBindingConnector(int connectionId, ::Platform::Object^ target);
    
    private:
        void UnloadObject(::Windows::UI::Xaml::DependencyObject^ dependencyObject);
        void DisconnectUnloadedObject(int connectionId);
    
    private:
        bool _contentLoaded;
    
    
        private: ::Windows::UI::Xaml::Controls::Slider^ xaml_PageSlider;
        private: ::Windows::UI::Xaml::Controls::Button^ Find_File;
        private: ::Windows::UI::Xaml::Controls::AppBar^ TopAppBar1;
        private: ::Windows::UI::Xaml::Controls::StackPanel^ LeftPanel;
        private: ::Windows::UI::Xaml::Controls::StackPanel^ RightPanel;
        private: ::Windows::UI::Xaml::Controls::Button^ Search;
        private: ::Windows::UI::Xaml::Controls::Button^ ZoomIn;
        private: ::Windows::UI::Xaml::Controls::Button^ ZoomOut;
        private: ::Windows::UI::Xaml::Controls::Button^ Contents;
        private: ::Windows::UI::Xaml::Controls::Button^ Links;
        private: ::Windows::UI::Xaml::Controls::Button^ Reflow;
        private: ::Windows::UI::Xaml::Controls::TextBox^ FindBox;
        private: ::Windows::UI::Xaml::Controls::Button^ PrevSearch;
        private: ::Windows::UI::Xaml::Controls::Button^ NextSearch;
        private: ::Windows::UI::Xaml::Controls::Grid^ xaml_OutsideGrid;
        private: ::Windows::UI::Xaml::Controls::Grid^ xaml_MainGrid;
        private: ::Windows::UI::Xaml::Controls::WebView^ xaml_WebView;
        private: ::Windows::UI::Xaml::Controls::StackPanel^ xaml_ProgressStack;
        private: ::Windows::UI::Xaml::Controls::StackPanel^ xaml_PrintStack;
        private: ::Windows::UI::Xaml::Controls::StackPanel^ xaml_PasswordStack;
        private: ::Windows::UI::Xaml::Controls::PasswordBox^ xaml_password;
        private: ::Windows::UI::Xaml::Controls::ProgressBar^ xaml_PrintProgress;
        private: ::Windows::UI::Xaml::Controls::ProgressBar^ xaml_Progress;
        private: ::Windows::UI::Xaml::Controls::Canvas^ xaml_zoomCanvas;
        private: ::Windows::UI::Xaml::Controls::ListView^ xaml_ListView;
        private: ::Windows::UI::Xaml::Controls::FlipView^ xaml_horiz_flipView;
        private: ::Windows::UI::Xaml::Controls::FlipView^ xaml_vert_flipView;
    };
}

